Repository depromeet/Ding-dong-fe, pull requests merged in 2023-06, with the labels that each got.

#8 Dep 30 login
  .gitignore
  .vscode/settings.json
  package.json
  pnpm-lock.yaml
  public/assets/images/kakao_login_large_wide.png
  public/assets/images/planet.png
  src/app/Provider.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/app/api/auth/signin/kakaoLoginButton.tsx
  src/app/api/auth/signin/page.tsx
  src/app/globals.css
  src/app/home/page.tsx
  src/app/onboarding/page.tsx
  src/app/onboarding/questions.tsx
  src/app/onboarding/sendNickname.tsx
  src/app/page.tsx
Labels: feat

#5 Dep 37 design system setting
  .storybook/preview.tsx
  .vscode/settings.json
  src/app/Provider.tsx
  src/app/api/auth/signin/kakaoLoginButton.tsx
  src/app/api/auth/signin/page.tsx
  src/app/globals.css
  src/app/home/page.tsx
  src/app/layout.tsx
  src/styles/globals.css
  tailwind.config.js
Labels: feat

#6 Dep 42 chromatic
  .github/workflows/chromatic.yml
  build-storybook.log
  package.json
  pnpm-lock.yaml
Labels: feat

#10 Dep 32 fe GitHub action script and Dockerize
  .env.development
  .env.production
  .github/workflows/ci.yml
  .gitignore
  Dockerfile
  docker-compose.yml
  next.config.js
  pnpm-lock.yaml
  src/app/api/auth/[...nextauth]/route.ts
  src/components/Tester/index.tsx
Labels: feat

#13 Refactor: pnpm-lock.yaml 중복 설정 제거
  pnpm-lock.yaml
Labels: fix

#9 Add Add CODEOWNERS file
  .github/CODEOWNERS
Labels: feat

#7 Dep 38 fe button popup component
  .github/workflows/chromatic.yml
  .github/workflows/ci.yml
  .storybook/preview.tsx
  next.config.js
  package.json
  src/app/layout.tsx
  src/components/Button/Button.stories.tsx
  src/components/Button/Button.tsx
  src/components/Button/index.ts
  src/components/Popup/Popup.stories.tsx
  src/components/Popup/Popup.tsx
  src/components/Popup/index.ts
  src/components/Portal/Portal.tsx
  src/components/Portal/index.ts
  src/hooks/useIsMounted.ts
  src/hooks/usePopup.ts
Labels: feat

#15 Dep 58 fe tag component
  src/components/Tag/Tag.stories.tsx
  src/components/Tag/Tag.tsx
  src/components/Tag/index.ts
  src/types/user.d.ts
  tailwind.config.js
Labels: feat

#19 Feat: MSW 설정 변경
  src/mocks/index.ts
Labels: fix

#21 Add storybook viewport addon
  .storybook/main.ts
  .storybook/preview.tsx
  package.json
  pnpm-lock.yaml
  src/styles/globals.css
Labels: feat

#25 Dep 52 fe no planet main
  .storybook/preview.tsx
  src/app/communities/page.tsx
  src/app/page.tsx
  src/app/signin/page.jsx
  src/components/Button/Button.tsx
  src/components/Button/TextButton.stories.tsx
  src/components/Button/TextButton.tsx
  src/components/Button/index.ts
  src/components/Popup/usePopup.ts
  src/modules/PlanetEnterButtons/PlanetEnterButton.stories.tsx
  src/modules/PlanetEnterButtons/PlanetEnterButtons.tsx
  src/modules/PlanetEnterButtons/index.ts
Labels: feat

#22 Dep 67 Add ProfileStep component
  src/components/ResidentCardCreation/Form/index.ts
  src/components/ResidentCardCreation/index.ts
  src/modules/IdCardCreation/Form/IdCardForm.tsx
  src/modules/IdCardCreation/Form/index.ts
  src/modules/IdCardCreation/IdCardCreation.type.ts
  src/modules/IdCardCreation/IdCardSteps.stories.tsx
  src/modules/IdCardCreation/IdCardSteps.tsx
  src/modules/IdCardCreation/Step/ProfileStep.client.tsx
  src/modules/IdCardCreation/Step/index.ts
  src/modules/IdCardCreation/index.ts
Labels: feat

#23 Dep 74 fe id card
  public/assets/images/buddy.png
  public/assets/images/pipi.png
  public/assets/images/tobby.png
  public/assets/images/true.png
  src/components/Tag/Tag.stories.tsx
  src/components/Tag/Tag.tsx
  src/modules/IdCard/IdCard.client.tsx
  src/modules/IdCard/IdCard.stories.tsx
  src/modules/IdCard/index.ts
  src/styles/globals.css
  src/types/user.d.ts
Labels: feat

#26 Dep 55 fe keyword input
  src/app/page.tsx
  src/components/Chip/Chip.stories.tsx
  src/components/Chip/Chip.tsx
  src/components/Chip/index.ts
  src/components/Icon/ArrowLeftIcon.tsx
  src/components/Icon/CancelIcon.tsx
  src/components/Icon/ChevronLeftIcon.tsx
  src/components/Icon/Icon.stories.tsx
  src/components/Icon/PlusIcon.tsx
  src/components/Icon/index.tsx
  src/components/KeywordInput/KeywordInput.stories.tsx
  src/components/KeywordInput/KeywordInput.tsx
  src/components/KeywordInput/index.ts
  src/components/KeywordInput/keywordInput.type.ts
  src/components/KeywordInput/useInputAutoSize.ts
  src/components/KeywordInput/useKeywordInput.hooks.ts
  src/components/Tester/Tester.stories.tsx
  src/components/Tester/index.tsx
  src/modules/IdCardCreation/Form/IdCardForm.tsx
  src/modules/IdCardCreation/IdCardSteps.tsx
  src/modules/IdCardCreation/Step/KeywordContentStep.client.tsx
  src/modules/IdCardCreation/Step/KeywordStep.client.tsx
  src/modules/IdCardCreation/Step/ProfileStep.client.tsx
  src/modules/IdCardCreation/Step/index.ts
  src/styles/globals.css
Labels: feat

#24 Tailwind util
  package.json
  pnpm-lock.yaml
  src/types/util.d.ts
  src/utils/tailwind.util.ts
Labels: feat

#28 Dep 64 fe swipper + 주민증 온보딩
  package.json
  pnpm-lock.yaml
  public/assets/images/explain-edit-id-card.png
  public/assets/images/explain-id-card.png
  public/assets/images/planet-with-shadow.png
  src/components/BottomSheet/BottomSheet.tsx
  src/components/BottomSheet/BottomSheetWrapper.tsx
  src/components/Icon/Icon.stories.tsx
  src/components/Icon/QuestionCircleIcon.tsx
  src/components/Icon/index.tsx
  src/components/Portal/AnimatedPortal.tsx
  src/components/Portal/Portal.tsx
  src/components/Portal/index.ts
  src/components/Swiper/Swiper.stories.tsx
  src/components/Swiper/Swiper.tsx
  src/components/Swiper/SwiperSlide.tsx
  src/components/Swiper/index.tsx
  src/modules/IdCardCreation/IdCardSteps.stories.tsx
  src/modules/IdCardCreation/IdCardSteps.tsx
  src/modules/IdCardCreation/Step/BoardingStep.client.tsx
  src/modules/IdCardCreation/Step/LoadingStep.client.tsx
  src/modules/IdCardCreation/Step/index.ts
Labels: feat

#30 Api type refactoring
  src/types/api/index.ts
  src/types/api/response.type.ts
  src/types/auth/index.ts
  src/types/auth/response.type.ts
  src/types/community/dto.ts
  src/types/community/dto.type.ts
  src/types/community/index.ts
  src/types/community/response.ts
  src/types/community/response.type.ts
  src/types/idCard/dto.type.ts
  src/types/idCard/index.ts
  src/types/idCard/request.ts
  src/types/idCard/request.type.ts
  src/types/idCard/response.ts
  src/types/idCard/response.type.ts
  src/types/user/dto.type.ts
  src/types/user/index.ts
  src/types/user/request.ts
  src/types/user/request.type.ts
  src/types/user/response.ts
  src/types/user/response.type.ts
Labels: refactor

#32 Refactor: husky lint 명령어 수정
  .husky/pre-commit
Labels: fix

#36 Dep69 Add ImagePreview component
  src/components/Icon/CancelIcon.tsx
  src/modules/IdCardCreation/IdCardCreation.type.ts
  src/modules/IdCardCreation/Step/ImagePreview.client.tsx
  src/modules/IdCardCreation/Step/KeywordContentStep.client.tsx
Labels: feat

#41 Refactor id card
  src/app/id-card/[id]/page.tsx
  src/components/Tag/Tag.tsx
  src/lib/api/config/api.types.ts
  src/lib/api/config/requestUrl.ts
  src/lib/api/domain/idCard.api.ts
  src/mocks/handlers.ts
  src/mocks/idCard/idCard.mock.ts
  src/mocks/idCard/idCard.mockHandler.ts
  src/modules/IdCard/IdCard.client.tsx
  src/modules/IdCardDetail/Intro/Intro.server.tsx
  src/modules/IdCardDetail/Intro/Intro.stories.tsx
  src/modules/IdCardDetail/KeywordContentCard/KeywordContentCard.server.tsx
  src/types/id-cards.type.ts
  src/types/idCard/dto.type.ts
  src/types/idCard/response.type.ts
Labels: refactor

#43 Dep 84 pxr
  src/components/Chip/Chip.tsx
  src/components/KeywordInput/KeywordInput.tsx
  src/modules/IdCardCreation/Step/BoardingStep.client.tsx
  src/modules/IdCardCreation/Step/LoadingStep.client.tsx
  src/modules/IdCardCreation/Step/ProfileStep.client.tsx
  tailwind.config.js
Labels: feat

#37 Dep 78 svg component
  src/components/Icon/ArrowLeftIcon.tsx
  src/components/Icon/CancelIcon.tsx
  src/components/Icon/ChevronLeftIcon.tsx
  src/components/Icon/Icon.stories.tsx
  src/components/Icon/PlusIcon.tsx
  src/components/Icon/QuestionCircleIcon.tsx
  src/components/Svg/Svg.tsx
  src/components/Svg/index.tsx
Labels: feat

#42 Refactor api type
  src/app/id-card/[id]/page.tsx
  src/components/Tag/Tag.tsx
  src/lib/api/domain/idCard.api.ts
  src/mocks/idCard/idCard.mock.ts
  src/modules/IdCard/IdCard.client.tsx
  src/modules/IdCardDetail/Intro/Intro.server.tsx
  src/modules/IdCardDetail/KeywordContentCard/KeywordContentCard.server.tsx
  src/types/api/response.type.ts
  src/types/auth/model.type.ts
  src/types/auth/response.type.ts
  src/types/community/dto.type.ts
  src/types/community/index.ts
  src/types/community/model.type.ts
  src/types/community/response.type.ts
  src/types/idCard/index.ts
  src/types/idCard/model.type.ts
  src/types/idCard/request.type.ts
  src/types/idCard/response.type.ts
  src/types/user/index.ts
  src/types/user/model.type.ts
  src/types/user/request.type.ts
  src/types/user/response.type.ts
Labels: refactor

#40 Dep 69 Add style of KeywordContentCard and KeywordContnetEditCard
  src/app/id-card/[id]/page.tsx
  src/modules/IdCardCreation/Card/KeywrodContentEditCard.client.tsx
  src/modules/IdCardCreation/Card/index.tsx
  src/modules/IdCardCreation/IdCardCreation.type.ts
  src/modules/IdCardCreation/IdCardCreationSteps.tsx
  src/modules/IdCardCreation/Step/ImagePreview.client.tsx
  src/modules/IdCardCreation/Step/KeywordContentStep.client.tsx
  src/modules/IdCardCreation/Step/ProfileStep.client.tsx
  src/modules/IdCardDetail/KeywordContentCard/KeywordContentCard.server.tsx
  src/modules/IdCardDetail/KeywordContentCard/KeywordContentCard.stories.tsx
  src/styles/globals.css
  src/types/idCard/creation.type.ts
  src/types/idCard/dto.type.ts
  src/types/idCard/index.ts
  src/types/idCard/request.type.ts
Labels: feat

#35 Refactor IdCardCreation component naming
  .eslintrc.json
  src/app/id-card/[id]/page.tsx
  src/modules/IdCardCreation/Card/KeywrodContentEditCard.client.tsx
  src/modules/IdCardCreation/Card/index.tsx
  src/modules/IdCardCreation/Form/IdCardCreationForm.tsx
  src/modules/IdCardCreation/Form/index.ts
  src/modules/IdCardCreation/IdCardCreation.type.ts
  src/modules/IdCardCreation/IdCardCreationSteps.stories.tsx
  src/modules/IdCardCreation/IdCardCreationSteps.tsx
  src/modules/IdCardCreation/Step/ImagePreview.client.tsx
  src/modules/IdCardCreation/Step/KeywordContentStep.client.tsx
  src/modules/IdCardCreation/Step/ProfileStep.client.tsx
  src/modules/IdCardCreation/index.ts
  src/modules/IdCardDetail/KeywordContentCard/KeywordContentCard.server.tsx
  src/modules/IdCardDetail/KeywordContentCard/KeywordContentCard.stories.tsx
  src/styles/globals.css
  src/types/idCard/creation.type.ts
  src/types/idCard/index.ts
  src/types/idCard/model.type.ts
  src/types/idCard/request.type.ts
Labels: feat, refactor

#39 Dep 70 complete step
  .storybook/preview.tsx
  src/app/id-card/[id]/page.tsx
  src/modules/IdCard/IdCard.client.tsx
  src/modules/IdCardCreation/Card/KeywrodContentEditCard.client.tsx
  src/modules/IdCardCreation/Form/IdCardCreationForm.tsx
  src/modules/IdCardCreation/IdCardCreationSteps.stories.tsx
  src/modules/IdCardCreation/IdCardCreationSteps.tsx
  src/modules/IdCardCreation/Step/CompleteStep.client.tsx
  src/modules/IdCardCreation/Step/KeywordContentStep.client.tsx
  src/modules/IdCardDetail/Intro/Intro.server.tsx
  src/modules/IdCardDetail/Intro/Intro.stories.tsx
  src/modules/IdCardDetail/KeywordContentCard/KeywordContentCard.server.tsx
  src/modules/IdCardDetail/KeywordContentCard/KeywordContentCard.stories.tsx
  src/types/idCard/index.ts
Labels: feat

#49 Dep 80 fe id cards list
  package.json
  pnpm-lock.yaml
  src/app/communities/[id]/layout.tsx
  src/app/communities/[id]/page.tsx
  src/hooks/api/community.query.ts
  src/hooks/api/queryKey.type.ts
  src/lib/api/domain/community.api.ts
  src/lib/tanstackQuery/getQueryClient.tsx
  src/mocks/community/community.mock.ts
  src/mocks/community/community.mockHandler.ts
  src/mocks/handlers.ts
  src/modules/CommnuityIdCards/CommunityIdCards.client.tsx
  src/modules/CommnuityIdCards/index.ts
  src/types/community/model.type.ts
  src/types/community/request.type.ts
  src/types/community/response.type.ts
Labels: feat

#44 Dep 86 Text Input component
  .eslintrc.json
  src/components/TextInput/TextInput.stories.tsx
  src/components/TextInput/TextInputBorder.tsx
  src/components/TextInput/TextInputContent.tsx
  src/components/TextInput/TextInputLabel.tsx
  src/components/TextInput/TextInputWrapper.tsx
  src/components/TextInput/index.tsx
  src/components/TextInput/useTextInput.ts
  src/modules/IdCardCreation/Step/ProfileStep.client.tsx
Labels: feat

#38 Dep 45 login api
  src/app/Provider.tsx
  src/app/accounts/callApiTest.tsx
  src/app/accounts/page.tsx
  src/app/api/auth/signin/sessionRedirect.tsx
  src/app/auth/[...nextauth]/route.ts
  src/app/auth/signin/kakaoLoginButton.client.tsx
  src/app/auth/signin/page.tsx
  src/app/auth/signin/signInProviders.server.tsx
  src/lib/api/config/api.types.ts
  src/lib/api/config/interceptor.ts
  src/lib/api/config/privateFetch.ts
  src/lib/api/config/publicFetch.ts
  src/lib/api/config/requestUrl.ts
  src/middleware.ts
  src/types/auth/response.type.ts
  src/utils/auth/tokenHandlers.ts
Labels: feat

#46 Dep 69 Add style and feature of ImagePreview
  src/components/Icon/CameraIcon.tsx
  src/components/Icon/Icon.stories.tsx
  src/components/Icon/index.tsx
  src/components/ProfileImageEdit/ProfileImageEdit.client.tsx
  src/components/ProfileImageEdit/index.ts
  src/modules/IdCardCreation/Card/KeywrodContentEditCard.client.tsx
  src/modules/IdCardCreation/Step/ImagePreview.client.tsx
  src/modules/IdCardCreation/Step/KeywordContentImage.client.tsx
  src/modules/IdCardCreation/Step/ProfileStep.client.tsx
  src/modules/IdCardCreation/Step/index.ts
  src/modules/IdCardDetail/KeywordContentCard/KeywordContentCard.server.tsx
  src/types/idCard/creation.type.ts
Labels: feat

#51 Remove eslint warning
  .eslintrc.json
  src/app/communities/[id]/page.tsx
  src/components/BottomSheet/BottomSheet.tsx
  src/components/Chip/Chip.tsx
  src/components/KeywordInput/KeywordInput.tsx
  src/components/KeywordInput/useInputAutoSize.ts
  src/components/KeywordInput/useKeywordInput.hooks.ts
  src/components/Popup/Popup.stories.tsx
  src/lib/api/config/api.types.ts
  src/modules/IdCardCreation/Form/IdCardCreationForm.tsx
  src/modules/IdCardCreation/IdCardCreationSteps.stories.tsx
  src/modules/IdCardCreation/Step/CompleteStep.client.tsx
  src/modules/IdCardCreation/Step/KeywordContentImage.client.tsx
  src/modules/IdCardCreation/Step/LoadingStep.client.tsx
  src/modules/IdCardDetail/KeywordContentCard/KeywordContentCard.stories.tsx
  src/modules/PlanetEnterButtons/PlanetEnterButtons.client.tsx
Labels: feat

#56 Fix: storybook alias
  .storybook/preview.tsx
Labels: feat

#50 Dep 81 community infos
  src/app/communities/[id]/layout.tsx
  src/app/communities/[id]/page.tsx
  src/components/BottomNavigation/BottomNavigation.tsx
  src/lib/api/config/requestUrl.ts
  src/lib/api/domain/community.api.ts
  src/mocks/community/community.mock.ts
  src/mocks/community/community.mockHandler.ts
  src/modules/CommunityDetail/CommunityDetail.server.tsx
  src/modules/CommunityDetail/CommunityDetail.stories.tsx
  src/modules/CommunityDetail/index.ts
  src/modules/CommunityIdCards/CommunityIdCards.client.tsx
  src/modules/CommunityIdCards/index.ts
  src/types/community/model.type.ts
  src/types/community/response.type.ts
Labels: feat

#57 Refactor: button height -> padding으로 수정
  src/components/Button/Button.tsx
Labels: refactor

#55 Fix/response api type
  src/app/id-card/[id]/page.tsx
  src/hooks/api/tester.query.ts
  src/lib/api/config/api.types.ts
  src/lib/api/config/interceptor.ts
  src/lib/api/domain/community.api.ts
  src/lib/api/domain/idCard.api.ts
  src/lib/api/domain/tester.api.ts
Labels: refactor

#58 Refactor api folder structure
  src/api/config/api.types.ts
  src/api/config/customError.ts
  src/api/config/interceptor.ts
  src/api/config/privateApi.ts
  src/api/config/privateFetch.ts
  src/api/config/publicApi.ts
  src/api/config/publicFetch.ts
  src/api/config/requestUrl.ts
  src/api/domain/community.api.ts
  src/api/domain/idCard.api.ts
  src/app/accounts/callApiTest.tsx
  src/app/accounts/page.tsx
  src/app/communities/[id]/page.tsx
  src/app/id-card/[id]/page.tsx
  src/components/Portal/Portal.tsx
  src/hooks/api/community.query.ts
  src/hooks/api/queryKey.type.ts
  src/hooks/api/tester.query.ts
  src/hooks/useIsMounted.hooks.ts
  src/lib/api/config/requestUrl.ts
  src/lib/api/domain/community.api.ts
  src/lib/api/domain/idCard.api.ts
  src/lib/api/domain/tester.api.ts
  src/middleware.ts
  src/mocks/community/community.mockHandler.ts
  src/mocks/idCard/idCard.mockHandler.ts
  src/modules/CommunityIdCards/CommunityIdCards.client.tsx
  src/types/community/index.ts
  src/types/community/request.type.ts
Labels: refactor

#54 Refactor/top navigation
  src/app/communities/[id]/layout.tsx
  src/app/id-card/[id]/page.tsx
  src/components/TopNavigation/TopNavigation.stories.tsx
  src/components/TopNavigation/TopNavigation.tsx
  src/components/TopNavigation/TopNavigationBackButton.tsx
  src/components/TopNavigation/TopNavigationLeft.tsx
  src/components/TopNavigation/TopNavigationRight.tsx
  src/components/TopNavigation/TopNavigationTitle.tsx
  src/components/TopNavigation/TopNavigationWrapper.tsx
  src/components/TopNavigation/index.ts
  src/components/TopNavigation/index.tsx
Labels: feat, refactor

#60 Dep 98 my page layout
  src/app/my-page/page.tsx
  src/components/Icon/GearFillIcon.tsx
  src/components/Icon/Icon.stories.tsx
  src/components/Icon/index.tsx
Labels: feat

#59 Dep 100 my page edit layout
  src/app/id-card/[id]/page.tsx
  src/app/my-page/edit/page.tsx
  src/app/my-page/layout.tsx
  src/modules/IdCardCreation/Card/KeywrodContentEditCard.client.tsx
  src/modules/IdCardCreation/Form/IdCardCreationForm.tsx
  src/modules/IdCardCreation/IdCardCreation.type.ts
  src/modules/IdCardCreation/IdCardCreationSteps.tsx
  src/modules/IdCardCreation/Step/KeywordContentStep.client.tsx
  src/modules/IdCardDetail/Intro/Intro.server.tsx
  src/modules/IdCardEditor/Form/IdCardEditorForm.tsx
  src/modules/IdCardEditor/Form/index.ts
  src/modules/IdCardEditor/IdCardEditor.tsx
  src/modules/IdCardEditor/IdCardEditor.type.ts
  src/modules/IdCardEditor/IdCardEditorSteps.stories.tsx
  src/modules/IdCardEditor/Step/EditKeywordContentStep.client.tsx
  src/modules/IdCardEditor/Step/EditKeywordStep.client.tsx
  src/modules/IdCardEditor/Step/EditProfileInfoStep.client.tsx
  src/modules/IdCardEditor/Step/index.ts
  src/modules/IdCardEditor/index.ts
  src/types/idCard/creation.type.ts
  src/types/idCard/index.ts
  src/types/idCard/model.type.ts
Labels: feat

#63 Refactor: communities -> planet 으로 수정
  src/app/page.tsx
  src/app/planet/[id]/layout.tsx
  src/app/planet/[id]/page.tsx
  src/app/planet/layout.tsx
  src/app/planet/page.tsx
  src/components/BottomNavigation/BottomNavigation.tsx
Labels: refactor

#67 Dep 90 layout variable
  .storybook/preview.tsx
  src/components/BottomNavigation/BottomNavigation.tsx
  src/components/TopNavigation/TopNavigationWrapper.tsx
  src/styles/globals.css
  tailwind.config.js
Labels: feat

#65 Rename: storybook convention
  src/components/BottomNavigation/BottomNavigation.stories.tsx
  src/components/BottomSheet/BottomSheet.stories.tsx
  src/components/Button/Button.stories.tsx
  src/components/Button/TextButton.stories.tsx
  src/components/Chip/Chip.stories.tsx
  src/components/Icon/Icon.stories.tsx
  src/components/KeywordInput/KeywordInput.stories.tsx
  src/components/Menu/Menu.stories.tsx
  src/components/Popup/Popup.stories.tsx
  src/components/Swiper/Swiper.stories.tsx
  src/components/Tag/Tag.stories.tsx
  src/components/TextArea/TextArea.stories.tsx
  src/components/TextInput/TextInput.stories.tsx
  src/components/TopNavigation/TopNavigation.stories.tsx
  src/modules/CommunityDetail/CommunityDetail.stories.tsx
  src/modules/IdCard/IdCard.stories.tsx
  src/modules/IdCardCreation/IdCardCreationSteps.stories.tsx
  src/modules/IdCardDetail/Intro/Intro.stories.tsx
  src/modules/IdCardDetail/KeywordContentCard/KeywordContentCard.stories.tsx
  src/modules/IdCardEditor/IdCardEditorSteps.stories.tsx
  src/modules/PlanetEnterButtons/PlanetEnterButton.stories.tsx
Labels: feat

#69 Dep 102 my page edit form
  src/components/Chip/Chip.tsx
  src/components/Icon/CancelIcon.tsx
  src/components/TextArea/TextAreaContent.tsx
  src/components/TextArea/useTextArea.ts
  src/components/TextInput/TextInputContent.tsx
  src/components/TextInput/useTextInput.ts
  src/modules/IdCardEditor/IdCardEditor.constant.ts
  src/modules/IdCardEditor/IdCardEditor.tsx
  src/modules/IdCardEditor/Step/EditKeywordContentStep.client.tsx
  src/modules/IdCardEditor/Step/EditKeywordStep.client.tsx
  src/modules/IdCardEditor/Step/EditProfileInfoStep.client.tsx
Labels: feat

#66 Dep 97 change planet
  src/api/domain/community.api.ts
  src/api/domain/idCard.api.ts
  src/app/planet/[id]/page.tsx
  src/mocks/community/community.mock.ts
  src/mocks/community/community.mockHandler.ts
  src/mocks/idCard/idCard.mockHandler.ts
  src/modules/CommunityIdCards/CommunityIdCards.client.tsx
  src/types/community/model.type.ts
  src/types/community/request.type.ts
  src/types/community/response.type.ts
Labels: feat

#68 Dep 109 Fix style of IdCardCreationSteps and add topnavigation on IdCardCreationSteps
  .storybook/preview.tsx
  .vscode/settings.json
  src/components/Chip/Chip.tsx
  src/components/KeywordInput/KeywordInput.tsx
  src/modules/IdCard/IdCard.client.tsx
  src/modules/IdCardCreation/Form/IdCardCreationForm.tsx
  src/modules/IdCardCreation/IdCardCreation.type.ts
  src/modules/IdCardCreation/IdCardCreationSteps.tsx
  src/modules/IdCardCreation/Step/BoardingStep.client.tsx
  src/modules/IdCardCreation/Step/CompleteStep.client.tsx
  src/modules/IdCardCreation/Step/KeywordContentStep.client.tsx
  src/modules/IdCardCreation/Step/KeywordStep.client.tsx
  src/modules/IdCardCreation/Step/LoadingStep.client.tsx
  src/modules/IdCardCreation/Step/ProfileStep.client.tsx
  src/modules/IdCardCreation/Step/index.ts
  src/modules/KeywordContentEditCard/KeywrodContentEditCard.client.tsx
  src/modules/KeywordContentEditCard/index.tsx
  src/styles/globals.css
  tailwind.config.js
Labels: feat

#71 Fix/keyword content edit card path
  src/modules/IdCardEditor/Step/EditKeywordContentStep.client.tsx
  src/modules/KeywordContentEditCard/KeywordContentEditCard.client.tsx
  src/modules/KeywordContentEditCard/index.tsx
Labels: fix

#72 Dep 105 admin planet setting page
  src/components/Button/Button.tsx
  src/components/Icon/KakaoIcon.tsx
  src/components/TextInput/TextInputBorder.tsx
  src/modules/CommunityAdmin/CommunityAdmin.stories.tsx
  src/modules/CommunityAdmin/CommunityAdmin.tsx
  src/modules/CommunityAdmin/CommunityAdminEdit.client.tsx
  src/modules/CommunityAdmin/CommunityAdminEditForm.client.tsx
  src/modules/CommunityProfile/CommunityBgImage.client.tsx
  src/modules/CommunityProfile/CommunityLogoImage.tsx
  src/modules/CommunityProfile/CommunityProfile.stories.tsx
  src/modules/CommunityProfile/CommunityProfile.tsx
  src/modules/CommunityProfile/index.ts
  src/modules/IdCardEditor/Step/EditKeywordContentStep.client.tsx
Labels: feat

#76 Dep 112 id card creation page
  src/app/id-card/create/page.tsx
  src/components/KeywordInput/KeywordInput.tsx
  src/modules/IdCardCreation/IdCardCreation.type.ts
  src/modules/IdCardCreation/IdCardCreationSteps.tsx
  src/modules/IdCardCreation/Step/BoardingStep.client.tsx
  src/modules/IdCardCreation/Step/CompleteStep.client.tsx
  src/modules/IdCardCreation/Step/KeywordContentStep.client.tsx
  src/modules/IdCardCreation/Step/KeywordStep.client.tsx
  src/modules/IdCardCreation/Step/ProfileStep.client.tsx
Labels: feat

#75 Dep 111 Add error validation on creation of id card
  src/app/id-card/create/page.tsx
  src/components/Chip/Chip.tsx
  src/components/KeywordInput/KeywordInput.tsx
  src/components/ProfileImageEdit/ProfileImageEdit.client.tsx
  src/components/TextArea/TextAreaWrapper.tsx
  src/components/TopNavigation/TopNavigationRight.tsx
  src/modules/IdCardCreation/Form/IdCardCreationForm.tsx
  src/modules/IdCardCreation/IdCardCreation.type.ts
  src/modules/IdCardCreation/IdCardCreationSteps.tsx
  src/modules/IdCardCreation/Step/BoardingStep.client.tsx
  src/modules/IdCardCreation/Step/CompleteStep.client.tsx
  src/modules/IdCardCreation/Step/KeywordContentStep.client.tsx
  src/modules/IdCardCreation/Step/KeywordStep.client.tsx
  src/modules/IdCardCreation/Step/ProfileStep.client.tsx
Labels: feat

#79 Fix: mypage build error 수정
  src/app/my-page/edit/page.tsx
Labels: fix

#73 Dep 97 change planet 2
  src/api/domain/community.api.ts
  src/app/notification/layout.tsx
  src/app/planet/[id]/layout.tsx
  src/app/planet/[id]/page.tsx
  src/components/Icon/ArrowVerticalIcon.tsx
  src/components/Icon/Icon.stories.tsx
  src/components/Icon/index.tsx
  src/components/TopNavigation/TopNavigationWrapper.tsx
  src/mocks/community/community.mock.ts
  src/modules/CommunityIdCards/CommunityIdCards.client.tsx
  src/modules/PlanetSelectorTopNavigation/CommunityList.client.tsx
  src/modules/PlanetSelectorTopNavigation/PlanetSelector.client.tsx
  src/modules/PlanetSelectorTopNavigation/PlanetSelectorTopNavigation.stories.tsx
  src/modules/PlanetSelectorTopNavigation/PlanetSelectorTopNavigation.tsx
  src/modules/PlanetSelectorTopNavigation/index.ts
  src/stores/community.store.ts
Labels: feat

#74 Dep 101 my page edit api
  .storybook/preview.tsx
  src/api/domain/idCard.api.ts
  src/app/my-page/edit/page.tsx
  src/components/KeywordInput/KeywordInput.tsx
  src/components/TextInput/TextInputWrapper.tsx
  src/mocks/idCard/idCard.mockHandler.ts
  src/modules/IdCardEditor/Form/IdCardEditorForm.tsx
  src/modules/IdCardEditor/IdCardEditor.tsx
  src/modules/IdCardEditor/IdCardEditor.type.ts
  src/modules/IdCardEditor/IdCardEditorSteps.stories.tsx
  src/modules/IdCardEditor/Step/EditKeywordContentStep.client.tsx
  src/modules/IdCardEditor/Step/EditKeywordStep.client.tsx
  src/modules/IdCardEditor/Step/EditProfileInfoStep.client.tsx
  src/types/idCard/model.type.ts
  src/types/idCard/request.type.ts
  src/types/idCard/response.type.ts
Labels: feat

#78 Dep 73 idcard create api
  src/api/domain/idCard.api.ts
  src/app/my-page/edit/page.tsx
  src/app/my-page/page.tsx
  src/mocks/community/community.mockHandler.ts
  src/mocks/handlers.ts
  src/mocks/idCard/idCard.mock.ts
  src/mocks/idCard/idCard.mockHandler.ts
  src/modules/IdCardCreation/Form/IdCardCreationForm.tsx
  src/modules/IdCardCreation/IdCardCreationSteps.stories.tsx
  src/modules/IdCardCreation/IdCardCreationSteps.tsx
  src/modules/IdCardCreation/Step/CompleteStep.client.tsx
  src/modules/IdCardCreation/Step/KeywordContentStep.client.tsx
  src/modules/IdCardEditor/IdCardEditorSteps.stories.tsx
  src/types/idCard/request.type.ts
  src/types/idCard/response.type.ts
Labels: feat

#80 Dep 110 my page
  src/api/domain/idCard.api.ts
  src/app/my-page/layout.tsx
  src/app/my-page/page.tsx
  src/mocks/idCard/idCard.mockHandler.ts
  src/modules/IdCardCreation/IdCardCreationSteps.stories.tsx
  src/modules/IdCardEditButton/IdCardEditButton.client.tsx
  src/modules/IdCardEditButton/IdCardEditButton.stories.tsx
  src/modules/IdCardEditButton/index.ts
  src/modules/PlanetCreationButton/PlanetCreationButton.client.tsx
  src/modules/PlanetCreationButton/PlanetCreationButton.stories.tsx
  src/modules/PlanetCreationButton/index.ts
  src/types/idCard/response.type.ts
Labels: feat

#85 Dep 100 my page 폴더 구조 수정
  src/api/domain/idCard.api.ts
  src/app/my-page/[id]/edit/page.tsx
  src/app/my-page/[id]/page.tsx
  src/app/my-page/empty/page.tsx
  src/app/my-page/layout.tsx
  src/app/my-page/page.tsx
  src/app/notification/layout.tsx
  src/app/planet/[id]/layout.tsx
  src/components/BottomNavigation/BottomNavigation.tsx
  src/modules/IdCardEditButton/IdCardEditButton.client.tsx
  src/modules/PlanetCreationButton/PlanetCreationButton.client.tsx
  src/modules/PlanetSelector/CommunityList.client.tsx
  src/modules/PlanetSelector/PlanetSelector.client.tsx
  src/modules/PlanetSelector/PlanetSelector.stories.tsx
  src/modules/PlanetSelector/index.ts
  src/modules/PlanetSelectorTopNavigation/PlanetSelectorTopNavigation.stories.tsx
  src/modules/PlanetSelectorTopNavigation/PlanetSelectorTopNavigation.tsx
  src/modules/PlanetSelectorTopNavigation/index.ts
Labels: feat

#86 Dep 118 설정페이지 (소속 커뮤니티 없는 경우)
  src/app/my-page/config/page.tsx
  src/modules/PlanetMenu/PlanetMenu.client.tsx
  src/modules/PlanetMenu/PlanetMenu.stories.tsx
  src/modules/PlanetMenu/index.ts
  src/modules/UserMenu/UserMenu.client.tsx
  src/modules/UserMenu/UserMenu.stories.tsx
  src/modules/UserMenu/index.ts
Labels: feat

#81 Dep 116 Add image upload api
  src/api/domain/image.api.ts
  src/components/ProfileImageEdit/ProfileImageEdit.client.tsx
  src/mocks/image/image.mock.ts
  src/mocks/image/image.mockHandler.ts
  src/modules/IdCardCreation/IdCardCreationSteps.stories.tsx
  src/modules/IdCardCreation/Step/KeywordContentImage.client.tsx
  src/modules/KeywordContentEditCard/KeywordContentEditCard.client.tsx
  src/types/image/index.ts
  src/types/image/model.type.ts
  src/types/image/request.type.ts
  src/types/image/response.type.ts
Labels: feat

#87 Dep 117 edit profile detail
  src/components/Chip/Chip.tsx
  src/modules/IdCardEditor/IdCardEditor.tsx
  src/modules/IdCardEditor/Step/EditKeywordContentStep.client.tsx
  src/modules/IdCardEditor/Step/EditProfileInfoStep.client.tsx
  src/modules/KeywordContentEditCard/KeywordContentEditCard.client.tsx
  src/types/image/model.type.ts
  src/utils/util.common.ts
Labels: feat

#88 Refactor: Swiper 에러 수정
  src/components/Swiper/SwiperSlide.tsx
Labels: fix

#91 Dep 119 confirm pop up
  src/components/BottomSheet/BottomSheet.stories.tsx
  src/components/BottomSheet/BottomSheetFooterButton.tsx
  src/components/Button/Button.stories.tsx
  src/components/Button/Button.tsx
  src/components/Button/TextButton.stories.tsx
  src/components/Button/TextButton.tsx
  src/components/ConfirmPopup/ConfirmDeleteKeyword/ConfirmDeleteKeyword.client.tsx
  src/components/ConfirmPopup/ConfirmDeleteKeyword/ConfirmDeleteKeyword.stories.tsx
  src/components/ConfirmPopup/ConfirmDeleteKeyword/index.ts
  src/components/ConfirmPopup/ConfirmUnSave/ConfirmUnSave.client.tsx
  src/components/ConfirmPopup/ConfirmUnSave/ConfirmUnSave.stories.tsx
  src/components/ConfirmPopup/ConfirmUnSave/index.ts
  src/components/ConfirmPopup/index.ts
  src/components/ConfirmPopup/useConfirmPopup.ts
  src/components/Popup/Popup.stories.tsx
  src/components/Popup/Popup.tsx
  src/modules/CommunityAdmin/CommunityAdmin.tsx
  src/modules/CommunityAdmin/CommunityAdminEditForm.client.tsx
  src/modules/CommunityProfile/CommunityBgImage.client.tsx
  src/modules/IdCardCreation/IdCardCreationSteps.stories.tsx
  src/modules/IdCardCreation/Step/BoardingStep.client.tsx
  src/modules/IdCardCreation/Step/CompleteStep.client.tsx
  src/modules/IdCardEditButton/IdCardEditButton.client.tsx
  src/modules/IdCardEditor/IdCardEditor.tsx
  src/modules/KeywordContentEditCard/KeywordContentEditCard.client.tsx
  src/modules/PlanetEnterButton/PlanetEnterButton.client.tsx
Labels: feat

#93 Dep 127 comment schema
  src/api/domain/comment.api.ts
  src/app/id-card/[id]/page.tsx
  src/mocks/comment/comment.mock.ts
  src/mocks/comment/comment.mockHandler.ts
  src/mocks/handlers.ts
  src/modules/Comment/Comment.client.tsx
  src/modules/Comment/index.ts
  src/modules/CommentList/CommentList.client.tsx
  src/modules/CommentList/index.ts
  src/types/comment/index.ts
  src/types/comment/model.type.ts
  src/types/comment/request.type.ts
  src/types/comment/response.type.ts
Labels: feat

#94 Prefetch util
  src/api/domain/community.api.ts
  src/api/domain/idCard.api.ts
  src/app/id-card/[id]/page.tsx
  src/app/my-page/config/page.tsx
  src/app/planet/[id]/page.tsx
  src/components/HydrationProvider/HydrationProvider.tsx
  src/components/HydrationProvider/index.ts
  src/modules/CommunityIdCards/CommunityIdCards.client.tsx
  src/modules/PlanetSelector/CommunityList.client.tsx
  src/types/community/request.type.ts
Labels: refactor

#97 Template button 빌드 에러 경로 수정
  src/components/Template/TemplateButton.tsx
Labels: fix

#98 Dep 143 comment api
  src/api/domain/comment.api.ts
  src/mocks/comment/comment.mockHandler.ts
  src/types/comment/request.type.ts
  src/types/comment/response.type.ts
Labels: feat

#96 Dep 128 comment UI
  src/api/domain/comment.api.server.ts
  src/api/domain/comment.api.ts
  src/app/id-card/[id]/page.tsx
  src/components/Icon/DashIcon.tsx
  src/components/Icon/HeartFillIcon.tsx
  src/components/Icon/HeartIcon.tsx
  src/components/Icon/Icon.stories.tsx
  src/components/Icon/index.tsx
  src/mocks/comment/comment.mock.ts
  src/mocks/comment/comment.mockHandler.ts
  src/modules/Comment/Comment.client.tsx
  src/modules/CommentList/Comment/Comment.client.tsx
  src/modules/CommentList/Comment/Comment.stories.tsx
  src/modules/CommentList/Comment/index.ts
  src/modules/CommentList/CommentCommon/Content.client.tsx
  src/modules/CommentList/CommentCommon/Header.client.tsx
  src/modules/CommentList/CommentCommon/LikeCount.client.tsx
  src/modules/CommentList/CommentCommon/LikeIcon.client.tsx
  src/modules/CommentList/CommentCommon/ReplyShowButton.client.tsx
  src/modules/CommentList/CommentCommon/ReplySubmitButton.client.tsx
  src/modules/CommentList/CommentCommon/UserProfile.client.tsx
  src/modules/CommentList/CommentCommon/index.ts
  src/modules/CommentList/CommentList.client.tsx
  src/modules/CommentList/CommentReplyList/CommentReply.client.tsx
  src/modules/CommentList/CommentReplyList/CommentReplyList.client.tsx
  src/modules/CommentList/CommentReplyList/index.ts
  src/types/comment/model.type.ts
  src/types/comment/response.type.ts
Labels: feat

#100 Refactor: 답글 숨기기, 펼치기 버튼 분리
  src/modules/CommentList/Comment/Comment.client.tsx
  src/modules/CommentList/CommentCommon/ReplyHideButton.client.tsx
  src/modules/CommentList/CommentCommon/ReplyShowButton.client.tsx
  src/modules/CommentList/CommentCommon/index.ts
Labels: feat

#99 Dep 130 comment detail
  src/mocks/comment/comment.mock.ts
  src/modules/CommentList/Comment/Comment.client.tsx
  src/modules/CommentList/Comment/Comment.stories.tsx
  src/modules/CommentList/CommentCommon/Content.client.tsx
  src/modules/CommentList/CommentReplyList/CommentReply.client.tsx
Labels: feat

#101 Dep 149 input comment ui
  src/api/domain/comment.api.ts
  src/api/domain/community.api.server.ts
  src/api/domain/community.api.ts
  src/api/domain/idCard.api.server.ts
  src/api/domain/user.api.ts
  src/app/accounts/page.tsx
  src/app/id-card/[id]/page.tsx
  src/app/planet/[id]/page.tsx
  src/components/Divider/Divider.tsx
  src/components/Icon/Icon.stories.tsx
  src/components/Icon/SendIcon.tsx
  src/components/Icon/index.tsx
  src/components/TextInput/TextInputBorder.tsx
  src/mocks/handlers.ts
  src/mocks/user/user.mock.ts
  src/mocks/user/user.mockHandler.ts
  src/modules/CommentInput/CommentInput.client.tsx
  src/modules/CommentInput/CommentInput.stories.tsx
  src/modules/CommentInput/index.ts
Labels: feat

#112 Dep 135 Add character post api
  src/api/domain/user.api.ts
  src/mocks/handlers.ts
  src/mocks/user/user.mockHandler.ts
  src/modules/Onboarding/Form/CharacterCreationForm.client.tsx
  src/modules/Onboarding/Form/CharacterCreationForm.helper.ts
  src/types/character/index.ts
  src/types/character/model.type.ts
  src/types/character/request.type.ts
Labels: feat

#102 Dep 133 Add character creation form
  public/assets/images/onboarding-planet.png
  public/assets/images/onboarding-question-food.png
  public/assets/images/onboarding-question-snack.png
  public/assets/images/onboarding-question-ticket.png
  public/assets/images/onboarding-question-ufo.png
  src/api/domain/user.api.ts
  src/app/onboarding/page.tsx
  src/app/onboarding/questions.tsx
  src/app/onboarding/sendNickname.tsx
  src/components/Template/TemplateButton.tsx
  src/components/Template/TemplateDescription.tsx
  src/components/Template/TemplateTitle.tsx
  src/mocks/user/user.mockHandler.ts
  src/modules/Onboarding/CharacterCreation.type.ts
  src/modules/Onboarding/CharacterCreationSteps.client.tsx
  src/modules/Onboarding/CharacterCreationSteps.stories.tsx
  src/modules/Onboarding/Form/CharacterCreationForm.client.tsx
  src/modules/Onboarding/Form/CharacterCreationForm.helper.ts
  src/modules/Onboarding/Form/index.ts
  src/modules/Onboarding/Question/CharacterQuestion.stories.tsx
  src/modules/Onboarding/Question/CharacterQuestion.tsx
  src/modules/Onboarding/Question/CharacterQuestion.type.ts
  src/modules/Onboarding/Step/CharacterBoardingStep.tsx
  src/modules/Onboarding/Step/CharacterCompleteStep.client.tsx
  src/modules/Onboarding/Step/CharacterCompleteStep.stories.tsx
  src/modules/Onboarding/Step/index.ts
  src/modules/Onboarding/index.ts
  src/types/user/model.type.ts
  src/types/user/request.type.ts
Labels: feat

#83 Add storybook cookie addon
  .storybook/main.ts
  .storybook/preview.tsx
  package.json
  pnpm-lock.yaml
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/mocks/image/image.mockHandler.ts
  src/mocks/server.ts
  src/modules/IdCardCreation/IdCardCreationSteps.stories.tsx
Labels: feat

#113 Dep 159 comment scheme
  src/api/domain/comment.api.server.ts
  src/api/domain/comment.api.ts
  src/app/id-card/[id]/page.tsx
  src/mocks/comment/comment.mock.ts
  src/mocks/comment/comment.mockHandler.ts
  src/modules/CommentList/Comment/Comment.client.tsx
  src/modules/CommentList/Comment/Comment.stories.tsx
  src/modules/CommentList/CommentList.client.tsx
  src/modules/CommentList/CommentReplyList/CommentReply.client.tsx
  src/modules/CommentList/CommentReplyList/CommentReplyList.client.tsx
  src/types/comment/model.type.ts
  src/types/comment/request.type.ts
Labels: feat

#114 Dep 129 comment like
  src/api/domain/comment.api.ts
  src/mocks/comment/comment.mockHandler.ts
  src/modules/CommentList/Comment/Comment.client.tsx
  src/modules/CommentList/Comment/CommentLike.client.tsx
  src/modules/CommentList/CommentCommon/LikeIcon.client.tsx
  src/modules/CommentList/CommentCommon/index.ts
  src/modules/CommentList/CommentReplyList/CommentReply.client.tsx
  src/modules/CommentList/CommentReplyList/CommentReplyLike.client.tsx
  src/types/comment/request.type.ts
  src/types/comment/response.type.ts
Labels: feat

#105 Dep 151 loading and error
  package.json
  pnpm-lock.yaml
  src/api/config/api.types.ts
  src/api/config/customError.ts
  src/api/config/interceptor.ts
  src/api/domain/comment.api.ts
  src/api/domain/idCard.api.server.ts
  src/app/id-card/[id]/components/CommentCount/CommentCount.tsx
  src/app/id-card/[id]/components/CommentCount/index.ts
  src/app/id-card/[id]/components/CommentList/CommentList.client.tsx
  src/app/id-card/[id]/components/CommentList/index.ts
  src/app/id-card/[id]/components/IdCardDetail/IdCardDetail.tsx
  src/app/id-card/[id]/components/IdCardDetail/index.ts
  src/app/id-card/[id]/page.tsx
  src/app/my-page/[id]/components/MyPageIdCard/MyPageIdCard.tsx
  src/app/my-page/[id]/components/MyPageIdCard/index.ts
  src/app/my-page/[id]/edit/components/MyPageEditIdCard/MyPageEditIdCard.tsx
  src/app/my-page/[id]/edit/components/MyPageEditIdCard/index.ts
  src/app/my-page/[id]/edit/page.tsx
  src/app/my-page/[id]/page.tsx
  src/app/planet/[id]/components/CommunityDetail/CommunityDetail.tsx
  src/app/planet/[id]/components/CommunityDetail/index.ts
  src/app/planet/[id]/components/CommunityIdCards/CommunityIdCards.client.tsx
  src/app/planet/[id]/components/CommunityIdCards/index.ts
  src/app/planet/[id]/page.tsx
  src/components/ErrorBoundary/RetryErrorBoundary.client.tsx
  src/components/ErrorBoundary/index.ts
  src/modules/CommunityDetail/CommunityDetail.stories.tsx
  src/modules/IdCardDetail/Intro.tsx
  src/modules/IdCardDetail/Intro/Intro.stories.tsx
  src/modules/IdCardDetail/Intro/index.ts
  src/modules/IdCardDetail/KeywordContentCard.tsx
  src/modules/IdCardDetail/KeywordContentCard/KeywordContentCard.stories.tsx
  src/modules/IdCardDetail/KeywordContentCard/index.ts
Labels: feat

#115 Fix planet image location on CharacterBoardingStep
  public/assets/images/onboarding-planet.png
  src/components/Template/TemplateContent.tsx
  src/modules/Onboarding/Step/CharacterBoardingStep.tsx
  tailwind.config.js
Labels: feat

#119 Feat: idcards 하나도 없을 때 문구 안보여주기
  src/app/planet/[id]/components/CommunityIdCards/CommunityIdCards.client.tsx
Labels: feat

#116 Dep 129 comment like count
  src/mocks/comment/comment.mock.ts
  src/modules/CommentList/Comment/Comment.client.tsx
  src/modules/CommentList/Comment/CommentLike.client.tsx
  src/modules/CommentList/CommentCommon/LikeCount.client.tsx
  src/modules/CommentList/CommentCommon/LikeIcon.client.tsx
  src/modules/CommentList/CommentCommon/index.ts
  src/modules/CommentList/CommentReplyList/CommentReply.client.tsx
  src/modules/CommentList/CommentReplyList/CommentReplyLike.client.tsx
  src/modules/CommentList/useLike.ts
  src/types/comment/model.type.ts
Labels: feat

#121 Dep 170 reply component
  src/modules/CommentInput/CommentInput.client.tsx
  src/modules/CommentInput/ReplyIndicator.client.tsx
  src/modules/CommentList/Comment/Comment.client.tsx
  src/modules/CommentList/CommentCommon/ReplySubmitButton.client.tsx
  src/modules/CommentList/CommentReplyList/CommentReply.client.tsx
  src/stores/comment.store.ts
Labels: feat

#125 Dep 171 reply comment
  src/api/domain/comment.api.ts
  src/modules/CommentInput/CommentInput.client.tsx
  src/utils/commentApi.util.ts
Labels: feat

#126 Dep 173 comment time
  src/modules/CommentList/CommentCommon/Header.client.tsx
  src/modules/Notification/NotificationList.tsx
  src/utils/time.util.ts
Labels: feat

#124 답글 없을 때 [답글 보여주기] UI 수정
  src/modules/CommentList/CommentCommon/Content.client.tsx
  src/modules/CommentList/CommentCommon/ReplyShowButton.client.tsx
Labels: fix

#130 Dep 176 delete comment
  src/api/domain/comment.api.ts
  src/modules/CommentList/Comment/Comment.client.tsx
  src/modules/CommentList/CommentCommon/DeleteButton.client.tsx
  src/modules/CommentList/CommentReplyList/CommentReply.client.tsx
  src/utils/commentApi.util.ts
Labels: feat

#129 Refactor: 주민증 생성 Boarding 페이지 수정
  public/assets/images/create-id-card-boarding-bottom.png
  public/assets/images/create-id-card-boarding.png
  src/modules/IdCardCreation/IdCardCreationSteps.stories.tsx
  src/modules/IdCardCreation/IdCardCreationSteps.tsx
  src/modules/IdCardCreation/Step/BoardingStep.client.tsx
Labels: style

#128 서버 기본 response 타입
  src/api/config/api.types.ts
  src/api/config/interceptor.ts
  src/mocks/comment/comment.mockHandler.ts
  src/mocks/community/community.mockHandler.ts
  src/mocks/idCard/idCard.mockHandler.ts
  src/mocks/image/image.mockHandler.ts
  src/mocks/mock.util.ts
  src/mocks/notification/notification.mockHandler.ts
  src/mocks/user/user.mockHandler.ts
Labels: feat
