Repository depromeet/Ding-dong-fe, pull requests merged in 2023-07, with the labels that each got.

#131 Dep 164 toast & portal 리팩토링
  .storybook/preview.tsx
  src/api/domain/comment.api.ts
  src/app/Provider.tsx
  src/app/layout.tsx
  src/components/Portal/Portal.tsx
  src/components/ToastMessage/ToastMessage.stories.tsx
  src/components/ToastMessage/ToastMessage.tsx
  src/components/ToastMessage/ToastMessageProvider.tsx
  src/components/ToastMessage/index.ts
  src/mocks/mock.util.ts
  src/modules/CommentList/Comment/Comment.client.tsx
  src/stores/tester.store.ts
  src/stores/toastMessage.store.ts
Labels: feat

#138 Dep 181 Fix validating invitation code and joining community api to match BE API
  src/api/domain/community.api.ts
  src/api/domain/user.api.ts
  src/app/invitation/[code]/page.tsx
  src/app/page.tsx
  src/mocks/community/community.mockHandler.ts
  src/mocks/user/user.mock.ts
  src/mocks/user/user.mockHandler.ts
  src/types/community/model.type.ts
  src/types/community/request.type.ts
  src/types/community/response.type.ts
  src/types/user/model.type.ts
  src/types/user/request.type.ts
  src/types/user/response.type.ts
Labels: feat

#139 Feat: 행성 만들기 버튼 연결하기
  src/modules/PlanetEnterButton/PlanetEnterButton.client.tsx
Labels: feat

#135 Dep 172 Add main flow
  public/assets/images/splash.png
  src/api/domain/community.api.ts
  src/api/domain/user.api.ts
  src/app/invitation/[code]/page.tsx
  src/app/page.tsx
  src/middleware.ts
  src/mocks/community/community.mockHandler.ts
  src/mocks/user/user.mock.ts
  src/mocks/user/user.mockHandler.ts
  src/modules/Onboarding/Step/CharacterBoardingStep.tsx
  src/types/community/model.type.ts
  src/types/community/request.type.ts
  src/types/community/response.type.ts
  src/types/user/model.type.ts
  src/types/user/request.type.ts
  src/types/user/response.type.ts
  src/utils/fetch.ts
  src/utils/route/route.ts
Labels: feat

#140 Feat: next image 설정을 위한 config 추가
  next.config.js
Labels: feat

#132 Dep 177 update comment count
  src/api/domain/comment/comment.api.server.ts
  src/api/domain/comment/comment.api.ts
  src/api/domain/comment/comment.helper.ts
  src/app/id-card/[id]/components/CommentCount/CommentCount.client.tsx
  src/app/id-card/[id]/components/CommentCount/index.ts
  src/app/id-card/[id]/components/CommentList/CommentList.client.tsx
  src/app/id-card/[id]/page.tsx
  src/mocks/comment/comment.mock.ts
  src/mocks/comment/comment.mockHandler.ts
  src/modules/CommentInput/CommentInput.client.tsx
  src/modules/CommentList/Comment/Comment.client.tsx
  src/modules/CommentList/CommentReplyList/CommentReply.client.tsx
Labels: feat

#136 로그인 페이지 디자인 수정
  public/assets/images/apple_login_large_wide.png
  public/assets/images/id_card_creation.png
  public/assets/images/memo.png
  public/assets/images/rocket.png
  public/assets/images/talk.png
  src/app/auth/signin/page.tsx
  src/components/Swiper/Swiper.stories.tsx
  src/components/Swiper/Swiper.tsx
  src/modules/IdCardCreation/Step/BoardingStep.client.tsx
  src/modules/LoginStep/AppleLoginButton.client.tsx
  src/modules/LoginStep/LoginStep.client.tsx
  src/modules/LoginStep/LoginStep.stories.tsx
  src/modules/LoginStep/index.ts
  src/modules/LoginStep/kakaoLoginButton.client.tsx
  src/modules/LoginStep/style.css
Labels: feat, style

#141 행성 생성 이후 초대링크 생성 및 clipboard 복사
  src/app/admin/community/create/result/layout.tsx
  src/app/admin/community/create/result/page.tsx
  src/components/ConfirmPopup/CopyInvitation/CopyInvitation.client.tsx
  src/components/ConfirmPopup/CopyInvitation/CopyInvitation.stories.tsx
  src/components/ConfirmPopup/CopyInvitation/index.ts
  src/components/ConfirmPopup/index.ts
  src/components/Popup/Popup.tsx
  src/mocks/comment/comment.mockHandler.ts
  src/mocks/community/community.mock.ts
  src/modules/CommunityAdmin/CommunityAdmin.tsx
  src/modules/CommunityAdmin/CommunityAdminEdit.client.tsx
  src/types/community/model.type.ts
Labels: feat

#146 Fix: 주민증 리스트 response 수정
  src/api/domain/community.api.ts
  src/app/planet/[id]/components/CommunityIdCards/CommunityIdCards.client.tsx
  src/mocks/community/community.mockHandler.ts
  src/types/community/response.type.ts
Labels: fix

#149 Fix: planet logo image #145
  src/modules/CommunityProfile/CommunityLogoImage.tsx
Labels: fix

#156 #151, #154 주민증 생성 관련 이슈
  src/modules/IdCardCreation/IdCardCreationSteps.tsx
  src/modules/KeywordContentEditCard/KeywordContentEditCard.client.tsx
Labels: fix

#162 #152 주민증 생성 form 태그 onSubmit 수정
  src/modules/IdCardCreation/Form/IdCardCreationForm.tsx
Labels: fix

#163 #157 기본 추천 키워드 관리
  src/constant/recommendKeyword.ts
  src/modules/IdCardCreation/Step/KeywordStep.client.tsx
  src/modules/IdCardEditor/IdCardEditor.constant.ts
  src/modules/IdCardEditor/Step/EditKeywordStep.client.tsx
Labels: fix

#164 초대링크 복사 수정
  src/api/config/requestUrl.ts
  src/app/admin/community/create/result/layout.tsx
  src/app/admin/community/create/result/page.tsx
Labels: feat

#165 Move id-card folder under planet folder
  src/app/planet/[communityId]/components/CommunityDetail/CommunityDetail.tsx
  src/app/planet/[communityId]/components/CommunityDetail/index.ts
  src/app/planet/[communityId]/components/CommunityIdCards/CommunityIdCards.client.tsx
  src/app/planet/[communityId]/components/CommunityIdCards/index.ts
  src/app/planet/[communityId]/components/IdCardCreatorButton/IdCardCreatorButton.client.tsx
  src/app/planet/[communityId]/components/IdCardCreatorButton/index.ts
  src/app/planet/[communityId]/id-card/[userId]/components/CommentCount/CommentCount.client.tsx
  src/app/planet/[communityId]/id-card/[userId]/components/CommentCount/index.ts
  src/app/planet/[communityId]/id-card/[userId]/components/CommentList/CommentList.client.tsx
  src/app/planet/[communityId]/id-card/[userId]/components/CommentList/index.ts
  src/app/planet/[communityId]/id-card/[userId]/components/IdCardDetail/IdCardDetail.tsx
  src/app/planet/[communityId]/id-card/[userId]/components/IdCardDetail/index.ts
  src/app/planet/[communityId]/id-card/[userId]/page.tsx
  src/app/planet/[communityId]/id-card/create/page.tsx
  src/app/planet/[communityId]/layout.tsx
  src/app/planet/[communityId]/page.tsx
Labels: feat

#168 행성만들기 steps에서 communityId추가
  src/app/planet/[communityId]/id-card/create/page.tsx
  src/modules/IdCardCreation/IdCardCreationSteps.tsx
Labels: fix

#161 Fix main flow cookie
  package.json
  src/api/domain/community.api.ts
  src/app/Provider.tsx
  src/app/invitation/[code]/page.tsx
  src/app/page.tsx
  src/middleware.ts
  src/mocks/community/community.mockHandler.ts
  src/modules/Onboarding/Step/CharacterCompleteStep.client.tsx
  src/utils/auth/getUserId.server.ts
  src/utils/cookie.util.ts
  src/utils/fetch.ts
  src/utils/route/route.ts
Labels: feat

#179 Feat: 주민증 만들기 이동 라우팅 수정
  src/app/planet/[communityId]/components/IdCardCreatorButton/IdCardCreatorButton.client.tsx
Labels: fix

#178 Feat: 커뮤니티 유저 정보 가져오기 api 추가
  src/api/domain/comment/comment.api.ts
  src/api/domain/community.api.ts
  src/api/domain/notification.api.ts
  src/types/community/model.type.ts
  src/types/community/response.type.ts
Labels: feat, fix

#176 Fix wrong order of character word
  src/modules/Onboarding/Form/CharacterCreationForm.helper.ts
Labels: fix

#183 Feat: 에러바운더리 디자인 수정
  src/components/ErrorBoundary/RetryErrorBoundary.client.tsx
Labels: feat

#185 마이페이지 관련 수정 (버튼 동작 및 ui 수정)
  src/app/my-page/empty/page.tsx
  src/components/Icon/PlusIcon.tsx
  src/modules/PlanetCreationButton/PlanetCreationButton.client.tsx
Labels: fix

#192 Fix/comment 3
  src/api/domain/comment/comment.api.server.ts
  src/api/domain/comment/comment.api.ts
  src/api/domain/comment/comment.helper.ts
  src/app/planet/[communityId]/id-card/[userId]/components/CommentList/CommentList.client.tsx
  src/app/planet/[communityId]/id-card/[userId]/page.tsx
  src/modules/CommentInput/CommentInput.client.tsx
  src/modules/IdCard/IdCard.client.tsx
  src/types/comment/request.type.ts
Labels: fix

#194 404 페이지
  public/assets/images/error-ufo.png
  src/app/not-found.tsx
Labels: feat

#196 Add routing logic
  package.json
  src/app/admin/planet/create/result/layout.tsx
  src/app/planet/[communityId]/components/IdCardCreatorButton/IdCardCreatorButton.client.tsx
  src/modules/CommentInput/CommentInput.stories.tsx
  src/modules/IdCardCreation/Step/CompleteStep.client.tsx
Labels: feat

#210 [7/3] Develop -> main 최신화
  .husky/pre-push
  .vscode/settings.json
  package.json
  public/assets/images/error-ufo.png
  src/api/config/requestUrl.ts
  src/api/domain/comment/comment.api.server.ts
  src/api/domain/comment/comment.api.ts
  src/api/domain/comment/comment.helper.ts
  src/api/domain/community.api.ts
  src/app/_page.tsx
  src/app/admin/community/[id]/edit/page.tsx
  src/app/admin/planet/[id]/edit/page.tsx
  src/app/admin/planet/[id]/page.tsx
  src/app/admin/planet/create/page.tsx
  src/app/admin/planet/create/result/layout.tsx
  src/app/admin/planet/create/result/page.tsx
  src/app/error.tsx
  src/app/invitation/[code]/page.tsx
  src/app/my-page/[communityId]/components/MyPageIdCard/MyPageIdCard.tsx
  src/app/my-page/[communityId]/components/MyPageIdCard/index.ts
  src/app/my-page/[communityId]/edit/components/MyPageEditIdCard/MyPageEditIdCard.tsx
  src/app/my-page/[communityId]/edit/components/MyPageEditIdCard/index.ts
  src/app/my-page/[communityId]/page.tsx
  src/app/my-page/[id]/edit/page.tsx
  src/app/my-page/empty/page.tsx
  src/app/my-page/page.tsx
  src/app/not-found.tsx
  src/app/planet/[communityId]/components/IdCardCreatorButton/IdCardCreatorButton.client.tsx
  src/app/planet/[communityId]/id-card/[userId]/components/CommentList/CommentList.client.tsx
  src/app/planet/[communityId]/id-card/[userId]/page.tsx
  src/app/planet/[communityId]/layout.tsx
  src/app/route.ts
  src/components/BottomNavigation/BottomNavigation.tsx
  src/components/ErrorBoundary/RetryErrorBoundary.client.tsx
  src/components/Icon/GearIcon.tsx
  src/components/Icon/Icon.stories.tsx
  src/components/Icon/PlusIcon.tsx
  src/components/Icon/index.tsx
  src/components/Template/TemplateWrapper.tsx
  src/middleware.ts
  src/modules/CommentInput/CommentInput.client.tsx
  src/modules/CommentInput/CommentInput.stories.tsx
  src/modules/CommunityAdmin/CommunityAdmin.tsx
  src/modules/CommunityAdmin/CommunityAdminEdit.client.tsx
  src/modules/CommunityProfile/CommunityBgImage.client.tsx
  src/modules/CommunityProfile/CommunityLogoImage.tsx
  src/modules/IdCard/IdCard.client.tsx
  src/modules/IdCardCreation/Step/CompleteStep.client.tsx
  src/modules/IdCardEditor/Step/EditKeywordContentStep.client.tsx
  src/modules/IdCardEditor/Step/EditProfileInfoStep.client.tsx
  src/modules/Onboarding/Step/CharacterCompleteStep.client.tsx
  src/modules/PlanetCreationButton/PlanetCreationButton.client.tsx
  src/modules/PlanetEnterButton/PlanetEnterButton.client.tsx
  src/modules/PlanetSelector/CommunityList.client.tsx
  src/modules/PlanetSelector/PlanetSelector.client.tsx
  src/stores/community.store.ts
  src/types/comment/request.type.ts
  src/types/community/model.type.ts
  src/types/user/response.type.ts
Labels: fix

#226 Add background image on invitation page
  public/assets/images/invitation.png
  src/app/invitation/[code]/page.tsx
Labels: feat

#227 Fix: 댓글 삭제
  src/api/domain/comment/comment.helper.ts
Labels: fix

#233 Fix/id card creation
  src/api/domain/community.api.server.ts
  src/api/domain/user.api.server.ts
  src/app/my-page/[communityId]/layout.tsx
  src/app/my-page/config/layout.tsx
  src/app/my-page/config/page.tsx
  src/app/my-page/layout.tsx
  src/modules/IdCard/IdCard.client.tsx
  src/modules/IdCardCreation/IdCardCreationSteps.tsx
Labels: fix

#235 Fix/no scroll login
  src/app/auth/signin/page.tsx
  src/modules/LoginStep/LoginStep.client.tsx
Labels: fix

#237 행성 이름이 최대일 때 UI가 꺠지는 부분을 수정했어요
  src/components/TopNavigation/TopNavigationLeft.tsx
  src/modules/CommunityAdmin/CommunityAdmin.tsx
  src/modules/PlanetSelector/PlanetSelector.client.tsx
Labels: fix

#241 Fix: 404 error #239
  src/app/not-found.tsx
Labels: fix

#257 Add title of community and characterType of user on complete step of creating id card
  src/api/domain/idCard.api.ts
  src/modules/IdCardCreation/IdCardCreationSteps.tsx
  src/modules/IdCardCreation/Step/CompleteStep.client.tsx
Labels: fix

#259 주민증 수정 관련 버그 (프로필 버튼, react-query cache errror)
  src/api/domain/idCard.api.ts
  src/app/my-page/[communityId]/edit/components/MyPageEditIdCard/MyPageEditIdCard.tsx
  src/app/my-page/[communityId]/edit/page.tsx
  src/app/my-page/[communityId]/layout.tsx
  src/app/my-page/[communityId]/page.tsx
  src/app/my-page/empty/page.tsx
  src/app/my-page/layout.tsx
  src/app/planet/[communityId]/id-card/[idCardId]/components/IdCardDetail/IdCardDetail.tsx
  src/app/planet/[communityId]/id-card/[idCardId]/page.tsx
  src/modules/IdCardEditor/IdCardEditor.tsx
  src/modules/IdCardEditor/IdCardEditorSteps.stories.tsx
  src/modules/IdCardEditor/Step/EditKeywordContentStep.client.tsx
Labels: fix

#260 주민증 생성 boadring페이지, 주민증이 없는 경우 마이페이지에 접근했을 때 처리
  src/api/domain/community.api.server.ts
  src/app/my-page/[communityId]/components/MyPageIdCard/MyPageIdCard.tsx
  src/app/my-page/[communityId]/page.tsx
  src/app/my-page/empty/page.tsx
  src/modules/CreateIdCardButton/CreateIdCardButton.client.tsx
  src/modules/CreateIdCardButton/CreateIdCardButton.stories.tsx
  src/modules/CreateIdCardButton/index.ts
  src/modules/IdCardCreation/Step/BoardingStep.client.tsx
Labels: fix

#262 주민증을 생성하지 않았을 때, 댓글창이 안보이는 이슈 및 기타 이슈
  src/api/domain/comment/comment.api.ts
  src/api/domain/user.api.ts
  src/components/ConfirmPopup/ConfirmCreateIdCard/ConfirmCreateIdCard.client.tsx
  src/components/ConfirmPopup/ConfirmCreateIdCard/ConfirmCreateIdCard.stories.tsx
  src/components/ConfirmPopup/ConfirmCreateIdCard/index.ts
  src/modules/CommentInput/ActiveCommentInput.client.tsx
  src/modules/CommentInput/CommentInput.client.tsx
  src/modules/CommentInput/DisabledCommentInput.client.tsx
  src/modules/CommunityAdmin/CommunityAdmin.tsx
  src/modules/IdCardCreation/Step/ProfileStep.client.tsx
  src/modules/Onboarding/Step/CharacterBoardingStep.tsx
Labels: fix

#265 행성 선택자 및 Bottom sheet 행성 동기화 문제
  src/app/planet/[communityId]/page.tsx
  src/components/BottomNavigation/BottomNavigation.tsx
  src/hooks/usePlanetNavigate.ts
  src/modules/PlanetSelector/PlanetSelector.client.tsx
Labels: fix

#268 대댓글 DTO 수정 사항 반영 및 #263해결
  src/api/domain/comment/comment.api.ts
  src/api/domain/comment/comment.helper.ts
  src/components/ProfileImageEdit/ProfileImageEdit.client.tsx
  src/mocks/comment/comment.mock.ts
  src/modules/CommentList/Comment/Comment.client.tsx
  src/modules/CommentList/CommentReplyList/CommentReply.client.tsx
  src/modules/CommentList/CommentReplyList/CommentReplyList.client.tsx
  src/types/comment/model.type.ts
Labels: fix

#270 관리자 페이지에 resetErrorboundary적용
  src/app/admin/planet/[id]/components/AdminPlanetDetailPage/AdminPlanetDetailPage.tsx
  src/app/admin/planet/[id]/components/AdminPlanetDetailPage/index.ts
  src/app/admin/planet/[id]/edit/components/PlanetAdminEdit/PlanetAdminEdit.tsx
  src/app/admin/planet/[id]/edit/components/PlanetAdminEdit/index.ts
  src/app/admin/planet/[id]/edit/page.tsx
  src/app/admin/planet/[id]/page.tsx
  src/app/admin/planet/create/result/layout.tsx
  src/app/admin/planet/create/result/page.tsx
Labels: feat

#272 댓글 작성 시간 및 좋아요 에러 처리
  src/modules/CommentList/Comment/Comment.client.tsx
  src/modules/CommentList/CommentCommon/Header.client.tsx
  src/modules/CommentList/CommentReplyList/CommentReply.client.tsx
  src/modules/Notification/NotificationItem.tsx
  src/modules/Notification/NotificationList.tsx
  src/utils/time.util.ts
Labels: fix

#277 행성 관리자 - 일반 멤버일 때 navi 유형 다르게 적용
  src/api/domain/comment/comment.api.ts
  src/api/domain/community.api.server.ts
  src/app/planet/[communityId]/page.tsx
  src/components/ProfileImageEdit/ProfileImageEdit.client.tsx
  src/modules/CommentInput/ActiveCommentInput.client.tsx
  src/types/community/model.type.ts
Labels: fix

#278 아이콘 전반적인 디자인 수정
  src/app/my-page/[communityId]/page.tsx
  src/app/my-page/empty/page.tsx
  src/app/planet/page.tsx
  src/components/Chip/Chip.tsx
  src/components/Icon/CancelCircleIcon.tsx
  src/components/Icon/CancelIcon.tsx
  src/components/Icon/GearFillIcon.tsx
  src/components/Icon/GearIcon.tsx
  src/components/Icon/Icon.stories.tsx
  src/components/Icon/ThreeDotsVerticalIcon.tsx
  src/components/Icon/index.tsx
  src/components/TopNavigation/TopNavigationBackButton.tsx
  src/modules/CommentInput/ReplyIndicator.client.tsx
  src/modules/IdCardCreation/Step/KeywordContentImage.client.tsx
  src/modules/KeywordContentEditCard/KeywordContentEditCard.client.tsx
Labels: fix

#279 develop작업(#278, #277) main에 반영
  src/api/domain/comment/comment.api.ts
  src/api/domain/community.api.server.ts
  src/app/my-page/[communityId]/page.tsx
  src/app/my-page/empty/page.tsx
  src/app/planet/[communityId]/page.tsx
  src/app/planet/page.tsx
  src/components/Chip/Chip.tsx
  src/components/Icon/CancelCircleIcon.tsx
  src/components/Icon/CancelIcon.tsx
  src/components/Icon/GearFillIcon.tsx
  src/components/Icon/GearIcon.tsx
  src/components/Icon/Icon.stories.tsx
  src/components/Icon/ThreeDotsVerticalIcon.tsx
  src/components/Icon/index.tsx
  src/components/ProfileImageEdit/ProfileImageEdit.client.tsx
  src/components/TopNavigation/TopNavigationBackButton.tsx
  src/modules/CommentInput/ActiveCommentInput.client.tsx
  src/modules/CommentInput/ReplyIndicator.client.tsx
  src/modules/IdCardCreation/Step/KeywordContentImage.client.tsx
  src/modules/KeywordContentEditCard/KeywordContentEditCard.client.tsx
  src/types/community/model.type.ts
Labels: fix

#282 Add redirect when tried to join the planet again
  src/api/config/customError.ts
  src/api/domain/community.api.ts
  src/app/invitation/[code]/page.tsx
Labels: feat

#283 Add object-cover css on profile user image
  src/modules/CommentList/CommentCommon/UserProfile.client.tsx
Labels: fix

#291 Fix/character image
  public/assets/images/BUDDY.png
  public/assets/images/PIPI.png
  public/assets/images/TOBBY.png
  public/assets/images/TRUE.png
Labels: fix

#293 대댓글 API 관련 변경 사항 반영 (대댓글 요청을 댓글 요청과 분리)
  src/api/domain/comment/comment.api.ts
  src/api/domain/comment/comment.helper.ts
  src/mocks/comment/comment.mock.ts
  src/mocks/comment/comment.mockHandler.ts
  src/mocks/user/user.mockHandler.ts
  src/modules/CommentList/Comment/Comment.client.tsx
  src/modules/CommentList/CommentCommon/CommentOptions.client.tsx
  src/modules/CommentList/CommentCommon/ReplyShowButton.client.tsx
  src/modules/CommentList/CommentCommon/index.ts
  src/modules/CommentList/CommentReplyList/CommentReply.client.tsx
  src/modules/CommentList/CommentReplyList/CommentReplyList.client.tsx
  src/types/comment/model.type.ts
  src/types/comment/request.type.ts
  src/types/comment/response.type.ts
Labels: fix

#294 Fix: mypage에서 주민증 상세보기 되도록 수정
  src/modules/IdCard/IdCard.client.tsx
Labels: fix

#295 Fix: BNB 아이콘 순서 변경
  src/components/BottomNavigation/BottomNavigation.tsx
Labels: style

#296 Fix: font 적용
  src/styles/globals.css
Labels: style

#299 Fix running CI and chromatic only when commits are pushed on main
  .github/workflows/chromatic.yml
  .github/workflows/ci.yml
Labels: fix

#302 Add idcard editor button disabled when editing id card is not valid
  src/modules/IdCardCreation/IdCardCreationSteps.tsx
  src/modules/IdCardEditor/IdCardEditor.tsx
Labels: fix

#303 Fix: max width 변경
  src/app/planet/[communityId]/components/CommunityDetail/CommunityDetail.tsx
  src/styles/globals.css
  tailwind.config.js
Labels: fix

#304 Fix/complete step design
  public/assets/images/planet-create-result-bg.png
  public/assets/images/planet-with-shadow.png
  src/app/admin/planet/create/result/page.tsx
  src/modules/IdCardCreation/Step/CompleteStep.client.tsx
Labels: style

#305 Revert "Fix/router (#300)"
  src/app/auth/callback/kakao/page.tsx
  src/app/auth/callback/kakao/route.ts
  src/app/my-page/route.ts
  src/app/page.tsx
  src/app/route.ts
  src/middleware.ts
Labels: fix

#306 [FE] - 마이페이지 - 주민증 수정 완료 안됨
  src/api/domain/idCard.api.ts
  src/modules/IdCardEditor/IdCardEditor.tsx
Labels: fix

#307 Id card edit design
  src/components/Chip/Chip.tsx
  src/modules/CommentList/CommentCommon/UserProfile.client.tsx
  src/modules/IdCardDetail/Intro.tsx
  src/modules/IdCardEditor/Step/EditKeywordContentStep.client.tsx
Labels: style

#308 Fix: 캐릭터마다 디폴트 프로필 이미지 넣기
  public/assets/images/default-profile-image-buddy.png
  public/assets/images/default-profile-image-pipi.png
  public/assets/images/default-profile-image-tobby.png
  public/assets/images/default-profile-image-true.png
  src/modules/IdCardCreation/Step/ProfileStep.client.tsx
Labels: fix

#309 refactor: 토스트 알람 위치 에러 수정
  src/components/ToastMessage/ToastMessageProvider.tsx
Labels: fix, style

#310 Feat: sentry 적용하기
  next.config.js
  package.json
  pnpm-lock.yaml
  sentry.client.config.ts
  sentry.edge.config.ts
  sentry.server.config.ts
Labels: feat

#312 댓글 좋아요 로직 및 UI 수정
  src/api/domain/comment/comment.api.ts
  src/api/domain/comment/comment.helper.ts
  src/mocks/comment/comment.mock.ts
  src/modules/CommentList/Comment/Comment.client.tsx
  src/modules/CommentList/CommentCommon/Header.client.tsx
  src/modules/CommentList/CommentCommon/LikeCount.client.tsx
  src/modules/CommentList/CommentCommon/LikeIcon.client.tsx
  src/modules/CommentList/CommentReplyList/CommentReply.client.tsx
  src/modules/CommentList/useLike.ts
  src/types/comment/model.type.ts
Labels: fix

#313 Fix/id card edit
  sentry.client.config.ts
  src/app/my-page/[communityId]/components/MyPageIdCard/MyPageIdCard.client.tsx
  src/app/my-page/[communityId]/components/MyPageIdCard/index.ts
  src/modules/IdCardEditButton/IdCardEditButton.client.tsx
  src/modules/KeywordContentEditCard/KeywordContentEditCard.client.tsx
Labels: fix

#314 댓글 신고
  src/components/ConfirmPopup/ConfirmDeleteComment/ConfirmDeleteComment.tsx
  src/components/ConfirmPopup/ConfirmDeleteComment/index.ts
  src/components/ConfirmPopup/SimpleConfirmPopup/index.ts
  src/components/ConfirmPopup/index.ts
  src/modules/CommentList/CommentCommon/DeleteButton.client.tsx
  src/modules/CommentList/CommentCommon/ReportButton.client.tsx
  src/modules/PlanetMenu/PlanetMenu.client.tsx
  src/modules/UserMenu/UserMenu.client.tsx
Labels: fix

#315 댓글 컴포넌트 폰트 수정
  src/components/Icon/DashIcon.tsx
  src/modules/CommentList/CommentCommon/Content.client.tsx
  src/modules/CommentList/CommentCommon/DeleteButton.client.tsx
  src/modules/CommentList/CommentCommon/LikeCount.client.tsx
  src/modules/CommentList/CommentCommon/ReplyShowButton.client.tsx
  src/modules/CommentList/CommentCommon/ReplySubmitButton.client.tsx
  src/modules/CommentList/CommentCommon/ReportButton.client.tsx
Labels: fix

#317 refactor: 주민증 수정 form 제출 이벤트 막기
  src/modules/IdCardEditor/Form/IdCardEditorForm.tsx
  src/modules/IdCardEditor/IdCardEditor.tsx
Labels: fix

#318 행성 수정 이후 최신화 에러 수정
  src/api/domain/community.api.ts
  src/app/admin/planet/[id]/components/AdminPlanetDetailPage/AdminPlanetDetailPage.tsx
  src/app/admin/planet/[id]/edit/components/PlanetAdminEdit/PlanetAdminEdit.tsx
  src/app/planet/[communityId]/components/CommunityDetail/CommunityDetail.tsx
  src/modules/CommunityAdmin/CommunityAdmin.stories.tsx
  src/modules/CommunityAdmin/CommunityAdmin.tsx
  src/modules/CommunityAdmin/CommunityAdminEdit.client.tsx
Labels: fix

#320 [주민증 수정] 키워트 추가 버튼 뿐만 아니라 키워드 영역을 눌렀을 때도 키워드 추가 페이지 진입
  src/modules/IdCardEditor/Step/EditKeywordContentStep.client.tsx
Labels: fix

#322 refactor: 댓글 창 막는 로직 수정
  src/modules/CommentInput/CommentInput.client.tsx
Labels: fix

#325 [FE] [주민증] 댓글 수 노출
  src/app/my-page/[communityId]/components/MyPageIdCard/MyPageIdCard.client.tsx
  src/components/Icon/ChatBubbleIcon.tsx
  src/components/Icon/Icon.stories.tsx
  src/components/Icon/index.tsx
  src/mocks/community/community.mock.ts
  src/mocks/idCard/idCard.mock.ts
  src/modules/IdCard/IdCard.client.tsx
  src/types/community/model.type.ts
  src/types/idCard/model.type.ts
Labels: fix

#326 주민증 생성, 수정 & 행성 소개 입력시 textarea 자동 높이 조절
  src/components/TextArea/TextAreaBorder.tsx
  src/components/TextArea/TextAreaContent.tsx
  src/components/TextArea/useAutoHeightTextArea.tsx
  src/hooks/useForwardRef.hooks.ts
  src/modules/CommunityAdmin/CommunityAdminEditForm.client.tsx
  src/modules/IdCardCreation/Step/ProfileStep.client.tsx
  src/modules/IdCardEditor/Step/EditProfileInfoStep.client.tsx
  src/modules/KeywordContentEditCard/KeywordContentEditCard.client.tsx
Labels: fix

#330 주민증 생성 디폴트 키워드
  src/modules/IdCardCreation/IdCardCreationSteps.tsx
Labels: fix

#329 [FE] 주민증 - 프로필사진 노출
  src/app/my-page/[communityId]/components/MyPageIdCard/MyPageIdCard.client.tsx
  src/components/KeywordInput/useKeywordInput.hooks.ts
  src/components/ProfileImageEdit/ProfileImageEdit.client.tsx
  src/mocks/community/community.mock.ts
  src/modules/IdCard/IdCard.client.tsx
  src/modules/IdCard/IdCard.stories.tsx
  src/modules/IdCardCreation/IdCardCreationSteps.stories.tsx
  src/modules/IdCardCreation/Step/CompleteStep.client.tsx
  src/types/community/model.type.ts
Labels: fix

#331 fix: 댓글 여러줄 작성되도록 수정
  src/components/TextArea/TextAreaBorder.tsx
  src/modules/CommentInput/ActiveCommentInput.client.tsx
Labels: fix

#332 알림 페이지 이동후 다시 홈으로 돌아오면, 원래 있던 행성이 아닌, 행성 목록 중 첫 번째 행성으로 이동합니다
  .vscode/launch.json
  src/components/BottomNavigation/BottomNavigation.tsx
  src/stores/community.store.ts
Labels: fix

#339 주민증 수정 : 키워드 삭제시 팝업 노출 안됨
  src/components/ConfirmPopup/useConfirmPopup.ts
  src/components/KeywordInput/KeywordInput.tsx
  src/modules/IdCardEditor/Step/EditKeywordStep.client.tsx
Labels: fix

#343 Fix: 댓글 입력창 조절
  src/modules/CommentInput/ActiveCommentInput.client.tsx
Labels: fix

#341 refactor: 403일 때는 토큰 발급 로직 실행 안되게 수정
  src/api/config/interceptor.client.ts
  src/api/config/interceptor.server.ts
  src/utils/auth/error.ts
Labels: fix

#344 Fix: comment input ui 수정
  src/modules/CommentInput/ActiveCommentInput.client.tsx
Labels: fix, style

#345 [FE] 주민증 수정시 키워드가 밀려써지는 경우
  src/modules/IdCardCreation/Step/KeywordContentStep.client.tsx
  src/modules/IdCardEditor/Step/EditKeywordContentStep.client.tsx
Labels: fix

#346 Fix: bottom nav,sheet max width
  src/components/BottomNavigation/BottomNavigation.tsx
  src/components/BottomSheet/BottomSheet.tsx
Labels: fix, style

#348 대댓글 작성시 댓글 총 개수가 반영되지 않은 버그 수정 및 댓글 작성 후 입력창 초기화
  src/api/domain/comment/comment.api.ts
  src/modules/CommentInput/ActiveCommentInput.client.tsx
Labels: fix

#349 행성리스트는 항상 refetch 되게 수정
  src/api/domain/community.api.ts
Labels: fix

#351 Fix: bg-color 수정
  src/app/layout.tsx
  src/app/notification/layout.tsx
  src/app/planet/[communityId]/id-card/create/page.tsx
  src/modules/CommunityAdmin/CommunityAdmin.tsx
  src/modules/CommunityAdmin/CommunityAdminCreate.client.tsx
  src/modules/CommunityAdmin/CommunityAdminEdit.client.tsx
  src/modules/CommunityAdmin/CommunityAdminEditForm.client.tsx
  src/modules/IdCardCreation/Form/IdCardCreationForm.tsx
  src/modules/IdCardCreation/Step/CompleteStep.client.tsx
  src/modules/Onboarding/Form/CharacterCreationForm.client.tsx
  src/modules/Onboarding/Question/CharacterQuestion.tsx
  src/styles/globals.css
Labels: style

#352 Fix: onboading image 안보이는 문제
  src/modules/Onboarding/Step/CharacterBoardingStep.tsx
Labels: fix

#355 토스트 알람 최대 길이 수정 및 최대 길이 tailwind 변수 관리 설정
  src/components/BottomNavigation/BottomNavigation.tsx
  src/components/BottomSheet/BottomSheet.tsx
  src/components/ToastMessage/ToastMessage.tsx
  src/components/ToastMessage/ToastMessageProvider.tsx
  src/components/TopNavigation/TopNavigationWrapper.tsx
  tailwind.config.js
Labels: fix, style

#356 댓글 입력 컴포넌트 최대 너비 조정
  src/app/planet/[communityId]/components/CommunityIdCards/CommunityIdCards.client.tsx
  src/app/planet/[communityId]/id-card/[idCardId]/components/CommentList/CommentList.client.tsx
  src/modules/CommentInput/ActiveCommentInput.client.tsx
  src/modules/CommentInput/CommentInput.client.tsx
  src/modules/CommentInput/DisabledCommentInput.client.tsx
Labels: fix, style

#357 refactor: 데스크톱에서 화면이 길어보이는 버그 수정
  src/modules/Notification/NotificationNoData.tsx
Labels: fix, style

#358 Feat/readme
  README.md
Labels: docs

#359 Fix: 모바일에서 scroll 생기는 문제
  src/app/admin/planet/create/result/page.tsx
  src/app/auth/signin/page.tsx
  src/app/error.tsx
  src/app/invitation/[code]/page.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  src/app/planet/[communityId]/page.tsx
  src/components/BottomSheet/BottomSheet.tsx
  src/modules/Onboarding/Step/CharacterBoardingStep.tsx
  src/modules/Onboarding/Step/CharacterCompleteStep.client.tsx
  src/styles/globals.css
  tailwind.config.js
Labels: fix

#353 Add default ding dong planet
  README.md
  src/app/my-page/[communityId]/page.tsx
  src/app/my-page/config/page.tsx
  src/app/planet/[communityId]/components/CommunityDetail/CommunityDetail.tsx
  src/app/planet/[communityId]/id-card/[idCardId]/page.tsx
  src/app/planet/[communityId]/page.tsx
  src/middleware.ts
  src/modules/CommunityAdmin/CommunityAdmin.tsx
  src/modules/CommunityProfile/CommunityProfile.tsx
  src/modules/IdCard/IdCard.client.tsx
  src/modules/Onboarding/Step/CharacterCompleteStep.client.tsx
  src/modules/PlanetEnterButton/PlanetEnterButton.client.tsx
  src/utils/variable.ts
Labels: feat

#360 [FE] 행성 기본선택자 0번 인덱스로 수정
  src/constant/planet.ts
  src/middleware.ts
  src/modules/PlanetSelector/PlanetSelector.client.tsx
  src/stores/community.store.ts
Labels: fix

#364 소속된 행성이 없는 페이지에서 상단 회색 여백 제거
  src/app/planet/page.tsx
Labels: fix, style

#366 [FE] 알람: 답글 좋아요 타입 추가
  src/types/notification/model.type.ts
Labels: fix
